name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_packages
      run: "sudo apt-get update; sudo apt-get -y install cppcheck-gui cppcheck clang valgrind"

    - name: all
      run: cd examples/T1; make all

    - name: cppcheck
      run: cd examples/T1; make cppcheck

    - name: cov
      run: cd examples/T1; make cov

    - name: valgrind
      run: cd examples/T1; make valgrind

    - name: sanitizer
      run: cd examples/T1; make sanitizer
